import { useEffect, useMemo, useState } from "react";
import { NavLink, useLocation, useNavigate } from "react-router-dom";
const glyph = (label) => function Glyph({ size = 17 }) { return <span className="admin-glyph" style={{ fontSize: Math.max(13, size - 1) }} aria-hidden>{label}</span>; };
const Menu = glyph("≡"); const X = glyph("×"); const LayoutDashboard = glyph("⌂"); const BookOpen = glyph("▣"); const FileText = glyph("□"); const CalendarDays = glyph("◷"); const Users = glyph("◉"); const UserRound = glyph("○"); const Bell = glyph("!"); const ClipboardList = glyph("☷"); const KeyRound = glyph("#"); const Inbox = glyph("▤"); const LogOut = glyph("↪"); const Plus = glyph("+"); const Search = glyph("⌕"); const Download = glyph("↓"); const Eye = glyph("◉"); const Pencil = glyph("✎"); const Trash2 = glyph("⌫"); const Check = glyph("✓"); const XCircle = glyph("×"); const Upload = glyph("↑"); const ChevronRight = glyph("›");

const PW_KEY = "yha_admin_pw";
const TABLES = {
  courses: { label: "Course", plural: "Courses", description: "Manage courses displayed in the public catalog.", create: true, fields: [["title","Title","text",true],["level","Level","text"],["duration","Duration","text"],["price","Price","number"],["image","Course image URL","url"],["subject","Catalog category","text"],["is_published","Visible to learners","select",false,["1","0"]],["featured","Featured","select",false,["0","1"]],["sort_order","Catalog order","number"],["enrollment_open","Enrollment open","select",false,["1","0"]],["description","Description","textarea"]] },
  subjects: { label: "Subject", plural: "Subjects", description: "Manage subjects assigned to courses.", create: true, fields: [["course_id","Course","course",true],["name","Subject name","text",true],["description","Description","textarea"]] },
  resources: { label: "Course resource", plural: "Course resources", description: "Publish PDF, ZIP, files, YouTube videos, and notes for enrolled students.", create: true, fields: [["course_id","Course","course",true],["title","Resource title","text",true],["resource_type","Resource type","select",false,["file","pdf","zip","youtube","note"]],["url","URL or uploaded file","resource-url"],["note","Note / description","textarea"],["sort_order","Display order","number"],["is_published","Visible to students","select",false,["1","0"]]] },
  sessions: { label: "Session", plural: "Sessions", description: "Manage course schedules and class time slots.", create: true, fields: [["course_id","Course","course",true],["name","Session name","text",true],["start_time","Start time","text"],["end_time","End time","text"]] },
  teachers: { label: "Teacher", plural: "Teachers", description: "Manage instructor profiles.", create: true, fields: [["name","Name","text",true],["email","Email","email"],["phone","Phone","text"],["specialization","Specialization","text"],["image","Image URL","url"],["bio","Bio","textarea"]] },
  course_teachers: { label: "Assignment", plural: "Teacher assignments", description: "Assign teachers to courses.", create: true, fields: [["course_id","Course","course",true],["teacher_id","Teacher","teacher",true]] },
  events: { label: "Event", plural: "Events", description: "Publish workshops and learning activities.", create: true, fields: [["title","Title","text",true],["category","Category","text"],["event_type","Type","text"],["date","Date","text"],["venue","Venue","text"],["duration","Duration","text"],["image","Image URL(s), separated by |","text"],["description","Description","textarea"]] },
  reviews: { label: "Review", plural: "Reviews", description: "Manage learner feedback displayed publicly.", create: true, fields: [["name","Student name","text",true],["course_id","Course","course"],["message","Message","textarea",true]] },
  notifications: { label: "Notification", plural: "Notifications", description: "Send targeted notifications to app users.", create: true, fields: [["title","Title","text",true],["message","Message","textarea",true],["student_id","Target student","student"],["course_id","Linked course","course"],["priority","Priority","select",false,["normal","high","urgent"]],["action_url","Action URL","url"],["publish_at","Publish at","datetime-local"],["expires_at","Expires at","datetime-local"]] },
  students: { label: "Student", plural: "Students", description: "Review complete student profiles and manage account status.", create: true, fields: [["student_id","Student ID","text"],["name","Full name","text",true],["email","Email","email"],["phone","Phone","text"],["father_name","Father name","text"],["mother_name","Mother name","text"],["nrc_number","NRC number","text"],["register_date","Register date","text"],["enroll_date","Enroll date","text"],["viber_phone","Viber phone","text"],["city","City","text"],["township","Township","text"],["birthday","Birthday","text"],["gender","Gender","select",false,["Male","Female","Other"]],["image","Image URL","url"],["education","Education","text"],["status","Status","select",false,["pending","active","inactive","completed"]],["course_id","Course","course"],["session_id","Session","session"]] },
  enrollments: { label: "Enrollment request", plural: "Enrollment requests", description: "Approve, reject, complete, or cancel student course requests.", create: false, fields: [["status","Status","select",false,["pending","approved","rejected","cancelled","completed"]],["admin_note","Admin note","textarea"]] },
  student_password_resets: { label: "Password-help request", plural: "Password-help requests", description: "Resolve student password-help requests after identity verification.", create: false, fields: [["status","Status","select",false,["pending","resolved","cancelled"]]] },
  contacts: { label: "Contact submission", plural: "Contact inbox", description: "Review messages submitted from the public contact form.", create: false, fields: [["name","Name","text"],["email","Email","email"],["message","Message","textarea"]] },
};

const NAV = [
  { label: "Overview", path: "/admin", icon: LayoutDashboard },
  { label: "Courses", path: "/admin/courses", icon: BookOpen, table: "courses" },
  { label: "Subjects", path: "/admin/subjects", icon: FileText, table: "subjects" },
  { label: "Resources", path: "/admin/resources", icon: FileText, table: "resources" },
  { label: "Sessions", path: "/admin/sessions", icon: CalendarDays, table: "sessions" },
  { label: "Teachers", path: "/admin/teachers", icon: Users, table: "teachers" },
  { label: "Assignments", path: "/admin/assignments", icon: ClipboardList, table: "course_teachers" },
  { label: "Events", path: "/admin/events", icon: CalendarDays, table: "events" },
  { label: "Reviews", path: "/admin/reviews", icon: FileText, table: "reviews" },
  { label: "Notifications", path: "/admin/notifications", icon: Bell, table: "notifications" },
  { label: "Enrollments", path: "/admin/enrollments", icon: ClipboardList, table: "enrollments" },
  { label: "Students", path: "/admin/students", icon: UserRound, table: "students" },
  { label: "Password help", path: "/admin/password-help", icon: KeyRound, table: "student_password_resets" },
  { label: "Contact inbox", path: "/admin/contacts", icon: Inbox, table: "contacts" },
];

function api(method, table, body) {
  const options = { method, headers: { "x-admin-password": sessionStorage.getItem(PW_KEY) || "" } };
  let url = "/api/admin";
  if (method === "GET") url += `?table=${encodeURIComponent(table)}`;
  else { options.headers["Content-Type"] = "application/json"; options.body = JSON.stringify({ ...body, table }); }
  return fetch(url, options).then(async (res) => { const data = await res.json().catch(() => ({})); if (!res.ok) { const e = new Error(data.error || `Request failed (${res.status})`); e.status = res.status; throw e; } return data; });
}

function csvCell(v) { return `"${String(v ?? "").replaceAll('"','""')}"`; }
function downloadStudents(rows, courses, sessions) {
  const columns = [["Student ID","student_id"],["Full Name","name"],["Email","email"],["Phone","phone"],["Father Name","father_name"],["Mother Name","mother_name"],["NRC Number","nrc_number"],["Viber Phone","viber_phone"],["City","city"],["Township","township"],["Birthday","birthday"],["Gender","gender"],["Education","education"],["Register Date","register_date"],["Enroll Date","enroll_date"],["Status","status"],["Password Set","password_set"],["Course","course_id"],["Session","session_id"]];
  const body = rows.map((r) => columns.map(([,key]) => { let v = r[key]; if (key === "password_set") v = r.password_set ? "Yes" : "No"; if (key === "course_id") v = courses.find((x) => String(x.id) === String(v))?.title || "Not assigned"; if (key === "session_id") v = sessions.find((x) => String(x.id) === String(v))?.name || "Not assigned"; return csvCell(v); }).join(","));
  const csv = "\ufeff" + [columns.map(([label]) => csvCell(label)).join(","), ...body].join("\r\n") + "\r\n";
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `yha-students-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url);
}

function Login({ onSuccess }) {
  const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(""); try { sessionStorage.setItem(PW_KEY, password); await api("GET", "courses"); onSuccess(); } catch (err) { sessionStorage.removeItem(PW_KEY); setError(err.message); } finally { setBusy(false); } }
  return <main className="admin-login-page"><div className="admin-login-card-react"><div className="admin-brand-mark">Y</div><p className="admin-eyebrow">YHA COMPUTER · CONTROL CENTER</p><h1>Admin Dashboard</h1><p>Sign in to manage courses, students, resources, and learner communication.</p><form onSubmit={submit}><label>Admin password<input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <div className="admin-alert error">{error}</div>}<button className="admin-primary full" disabled={busy}>{busy ? "Checking…" : "Sign in securely"}</button></form></div></main>;
}

function AdminDashboard() {
  const location = useLocation(); const navigate = useNavigate();
  const [authenticated, setAuthenticated] = useState(() => Boolean(sessionStorage.getItem(PW_KEY)));
  const [mobileOpen, setMobileOpen] = useState(false);
  const [resources, setResources] = useState({ courses: [], subjects: [], sessions: [], teachers: [], students: [] });
  const [notice, setNotice] = useState("");
  const nav = NAV.find((item) => item.path === location.pathname) || NAV[0];
  useEffect(() => { if (authenticated) Promise.all(Object.keys(resources).map((table) => api("GET", table).then((d) => [table, d.rows || []]).catch(() => [table, []]))).then((pairs) => setResources(Object.fromEntries(pairs))); }, [authenticated]);
  if (!authenticated) return <Login onSuccess={() => setAuthenticated(true)} />;
  function logout() { sessionStorage.removeItem(PW_KEY); setAuthenticated(false); navigate("/admin"); }
  const isOverview = location.pathname === "/admin" || location.pathname === "/admin/";
  return <div className="admin-react-app"><aside className={`admin-react-sidebar ${mobileOpen ? "open" : ""}`}><div className="admin-react-logo"><span>Y</span><div><b>YHA Admin</b><small>Control center</small></div><button className="admin-icon-button sidebar-close" onClick={() => setMobileOpen(false)}><X size={18}/></button></div><nav>{NAV.map((item) => { const Icon = item.icon; return <NavLink key={item.path} to={item.path} end={item.path === "/admin"} className={({isActive}) => `admin-react-nav ${isActive ? "active" : ""}`} onClick={() => setMobileOpen(false)}><Icon size={17}/><span>{item.label}</span></NavLink>; })}</nav><button className="admin-react-logout" onClick={logout}><LogOut size={17}/> Log out</button></aside>{mobileOpen && <button className="admin-sidebar-backdrop" onClick={() => setMobileOpen(false)} aria-label="Close navigation"/>}<section className="admin-react-main"><header className="admin-react-topbar"><button className="admin-icon-button mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={21}/></button><div><p className="admin-breadcrumb">YHA Computer <ChevronRight size={14}/> Admin <ChevronRight size={14}/> {nav.label}</p><h1>{isOverview ? "Good day, Admin" : nav.label}</h1></div><div className="admin-top-actions"><span className="admin-live-pill"><i/>Live</span><a href="/" className="admin-site-link-react">View site</a></div></header>{notice && <div className="admin-toast" onClick={() => setNotice("")}>{notice}</div>}{isOverview ? <Overview resources={resources} onNavigate={navigate}/> : <DataPage table={nav.table} resources={resources} setResources={setResources} notify={setNotice}/>}</section></div>;
}

function Overview({ resources, onNavigate }) { const cards = [["Courses","courses","/admin/courses",BookOpen,"orange"],["Students","students","/admin/students",UserRound,"blue"],["Enrollments","enrollments","/admin/enrollments",ClipboardList,"purple"],["Resources","resources","/admin/resources",FileText,"green"]]; const [enrollments, setEnrollments] = useState([]); useEffect(() => { api("GET","enrollments").then((d) => setEnrollments(d.rows || [])).catch(() => {}); }, []); return <div className="admin-overview"><div className="admin-welcome-card"><div><p className="admin-eyebrow">YHA COMPUTER · OPERATIONS</p><h2>Everything your team needs in one place.</h2><p>Manage the catalog, student lifecycle, learning resources, and targeted communication from one structured workspace.</p></div><div className="admin-welcome-orb"><LayoutDashboard size={38}/></div></div><div className="admin-stat-grid">{cards.map(([label,key,path,Icon,color]) => <button key={key} className="admin-stat-card" onClick={() => onNavigate(path)}><span className={`admin-stat-icon ${color}`}><Icon size={19}/></span><div><b>{resources[key]?.length ?? 0}</b><span>{label}</span></div><ChevronRight size={18}/></button>)}</div><div className="admin-overview-grid"><section className="admin-panel-react"><div className="admin-panel-heading"><div><p className="admin-eyebrow">WORK QUEUE</p><h3>Recent enrollment requests</h3></div><button className="admin-text-button" onClick={() => onNavigate("/admin/enrollments")}>View all</button></div>{enrollments.slice(0,5).map((row) => <div className="admin-queue-row" key={row.id}><div className="admin-avatar">{(row.student_name || "S").slice(0,1)}</div><div><b>{row.student_name || row.student_code}</b><small>{row.course_title || "Course request"}</small></div><span className={`admin-status ${row.status}`}>{row.status}</span></div>)}{!enrollments.length && <div className="admin-empty">No enrollment requests to review.</div>}</section><section className="admin-panel-react quick-actions"><div className="admin-panel-heading"><div><p className="admin-eyebrow">SHORTCUTS</p><h3>Quick actions</h3></div></div>{[["Add course","/admin/courses",Plus],["Review students","/admin/students",Users],["Publish resource","/admin/resources",Upload],["Send notification","/admin/notifications",Bell]].map(([label,path,Icon]) => <button key={path} onClick={() => onNavigate(path)}><span><Icon size={17}/></span>{label}<ChevronRight size={16}/></button>)}</section></div></div>; }

function DataPage({ table, resources, setResources, notify }) {
  const config = TABLES[table] || TABLES.courses; const [rows,setRows] = useState([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [query,setQuery] = useState(""); const [editing,setEditing] = useState(null); const [detail,setDetail] = useState(null); const [showForm,setShowForm] = useState(false);
  const load = () => { setLoading(true); api("GET",table).then((d) => setRows(d.rows || [])).catch((e) => setError(e.message)).finally(() => setLoading(false)); }; useEffect(load, [table]);
  const filtered = useMemo(() => { const q=query.toLowerCase().trim(); if (!q) return rows; return rows.filter((row) => Object.values(row).some((v) => String(v ?? "").toLowerCase().includes(q))); }, [rows,query]);
  async function save(values) { try { await api("POST", table, { action: editing?.id ? "update" : "create", id: editing?.id, values }); notify(`${config.label} ${editing?.id ? "updated" : "created"}.`); setShowForm(false); setEditing(null); load(); if (table in resources) api("GET",table).then((d) => setResources((old) => ({...old,[table]:d.rows || []}))); } catch (e) { setError(e.message); } }
  async function remove(id) { if (!confirm("Delete this record?")) return; try { await api("POST",table,{action:"delete",id}); notify("Record deleted."); load(); } catch(e) { setError(e.message); } }
  async function updateEnrollment(id,status) { const admin_note = prompt(`Optional note for ${status}:`, ""); if (admin_note === null) return; try { await api("POST", "enrollments", { action:"update", id, values:{status,admin_note} }); notify(`Enrollment ${status}.`); load(); } catch(e) { setError(e.message); } }
  async function generatePassword(id) { if (!confirm("Generate a new password for this student?")) return; try { const data=await api("POST","students",{action:"generate_password",id}); alert(`New password: ${data.password}`); notify("Replacement password generated."); } catch(e) { setError(e.message); } }
  function exportCsv() { downloadStudents(filtered, resources.courses || [], resources.sessions || []); }
  const title = table === "course_teachers" ? "Assignments" : config.plural;
  return <div className="admin-data-page"><div className="admin-page-intro"><div><p className="admin-eyebrow">MANAGEMENT MODULE</p><h2>{title}</h2><p>{config.description}</p></div><div className="admin-page-actions">{table === "students" && <button className="admin-secondary" onClick={exportCsv}><Download size={16}/> Export CSV</button>}{config.create && <button className="admin-primary" onClick={() => {setEditing(null);setShowForm(true);}}><Plus size={17}/> Add {config.label}</button>}</div></div>{error && <div className="admin-alert error">{error}<button onClick={() => setError("")}><X size={15}/></button></div>}<div className="admin-panel-react"><div className="admin-table-toolbar"><div className="admin-search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}…`} value={query} onChange={(e) => setQuery(e.target.value)}/></div><span className="admin-record-count">{filtered.length} records</span></div>{loading ? <div className="admin-loading">Loading {title.toLowerCase()}…</div> : !filtered.length ? <div className="admin-empty"><FileText size={28}/><b>No records found</b><span>{query ? "Try a different search." : "Create your first record to get started."}</span></div> : <div className="admin-table-wrap"><table className="admin-table-react"><thead><tr><th>Record</th><th>Details</th><th>Status</th><th className="actions-col">Actions</th></tr></thead><tbody>{filtered.map((row) => <RecordRow key={row.id} row={row} table={table} resources={resources} onEdit={() => {setEditing(row);setShowForm(true)}} onDelete={() => remove(row.id)} onDetail={() => setDetail(row)} onPassword={() => generatePassword(row.id)} onEnrollment={updateEnrollment}/>)}</tbody></table></div>}</div>{showForm && <RecordForm table={table} config={config} row={editing} resources={resources} onClose={() => {setShowForm(false);setEditing(null)}} onSave={save}/>} {detail && <StudentDetail row={detail} resources={resources} onClose={() => setDetail(null)}/>}</div>;
}

function displayName(row, table, resources) { if (table === "students") return row.name || row.student_id || "Student"; if (table === "enrollments") return row.student_name || row.student_code || "Enrollment request"; if (table === "student_password_resets") return row.student_name || row.student_code || "Password request"; if (table === "resources") return row.title || "Resource"; if (table === "course_teachers") return `${resources.courses?.find((x)=>String(x.id)===String(row.course_id))?.title || "Course"} assignment`; return row.title || row.name || row.subject || `${table} #${row.id}`; }
function RecordRow({row,table,resources,onEdit,onDelete,onDetail,onPassword,onEnrollment}) { const isStudent=table === "students"; const isEnrollment=table === "enrollments"; const isReset=table === "student_password_resets"; const status=row.status || (row.is_published === 1 || row.is_published === "1" ? "Published" : "Draft"); const subtitle = row.course_title || row.email || row.resource_type || row.message || row.description || row.student_email || ""; return <tr><td><div className="table-record"><span className="table-avatar">{displayName(row,table,resources).slice(0,1).toUpperCase()}</span><div><b>{displayName(row,table,resources)}</b><small>{subtitle}</small></div></div></td><td>{row.course_title || (row.course_id ? resources.courses?.find((x)=>String(x.id)===String(row.course_id))?.title : null) || row.session_name || row.phone || row.date || row.created_at || "—"}</td><td><span className={`admin-status ${String(status).toLowerCase().replaceAll(" ","-")}`}>{status}</span></td><td className="row-actions">{isStudent && <button title="View details" onClick={onDetail}><Eye size={16}/></button>}{isEnrollment && row.status === "pending" && <><button className="approve" title="Approve" onClick={() => onEnrollment(row.id,"approved")}><Check size={16}/></button><button className="reject" title="Reject" onClick={() => onEnrollment(row.id,"rejected")}><XCircle size={16}/></button></>}{isStudent && <button title="Generate password" onClick={onPassword}><KeyRound size={16}/></button>}{!isReset && configCanEdit(table) && <button title="Edit" onClick={onEdit}><Pencil size={16}/></button>}<button className="danger" title="Delete" onClick={onDelete}><Trash2 size={16}/></button></td></tr>; }
function configCanEdit(table) { return TABLES[table]?.create; }

function RecordForm({table,config,row,resources,onClose,onSave}) { const [values,setValues]=useState(() => Object.fromEntries(config.fields.map(([name]) => [name,row?.[name] ?? ""]))); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); function set(name,value){setValues((v)=>({...v,[name]:value}));} async function submit(e){e.preventDefault();setBusy(true);setError("");try{await onSave(values)}catch(e){setError(e.message)}finally{setBusy(false)}} return <div className="admin-modal-backdrop"><section className="admin-modal"><div className="admin-modal-header"><div><p className="admin-eyebrow">{row ? "EDIT RECORD" : "NEW RECORD"}</p><h3>{row ? `Edit ${config.label}` : `Add ${config.label}`}</h3></div><button className="admin-icon-button" onClick={onClose}><X size={20}/></button></div><form className="admin-form-grid" onSubmit={submit}>{config.fields.map(([name,label,type,required,options]) => <Field key={name} name={name} label={label} type={type} required={required} options={options} value={values[name]} set={set} resources={resources}/>) }{error && <div className="admin-alert error full-span">{error}</div>}<div className="admin-modal-actions"><button type="button" className="admin-secondary" onClick={onClose}>Cancel</button><button className="admin-primary" disabled={busy}>{busy ? "Saving…" : "Save record"}</button></div></form></section></div>; }
function Field({name,label,type,required,options,value,set,resources}) { if (type === "textarea") return <label className="full-span">{label}<textarea required={required} value={value || ""} onChange={(e)=>set(name,e.target.value)}/></label>; if (type === "select" || ["course","teacher","student","session"].includes(type)) { let list=options || []; if(type === "course") list=(resources.courses||[]).map((x)=>[x.id,x.title]); if(type === "teacher") list=(resources.teachers||[]).map((x)=>[x.id,x.name]); if(type === "student") list=(resources.students||[]).map((x)=>[x.id,`${x.name} (${x.student_id || x.id})`]); if(type === "session") list=(resources.sessions||[]).map((x)=>[x.id,x.name]); return <label>{label}<select required={required} value={value ?? ""} onChange={(e)=>set(name,e.target.value)}><option value="">Select…</option>{list.map((item)=>{const [v,l]=Array.isArray(item)?item:[item,item];return <option key={v} value={v}>{l}</option>})}</select></label>; } if(type === "resource-url") return <label className="full-span">{label}<input type="url" value={value || ""} onChange={(e)=>set(name,e.target.value)} placeholder="https://… or upload below"/><span className="field-hint">Small files up to 1.5MB can be converted to a public data URL.</span><input type="file" accept=".pdf,.zip,.txt,.doc,.docx,.png,.jpg,.jpeg" onChange={(e)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1.5*1024*1024){alert("File must be 1.5MB or smaller.");return}const reader=new FileReader();reader.onload=()=>set(name,String(reader.result));reader.readAsDataURL(file)}}/></label>; return <label>{label}<input required={required} type={type === "url" ? "url" : type} value={value ?? ""} onChange={(e)=>set(name,e.target.value)}/></label>; }
function StudentDetail({row,resources,onClose}) { const course=resources.courses?.find((x)=>String(x.id)===String(row.course_id))?.title || "Not assigned"; const session=resources.sessions?.find((x)=>String(x.id)===String(row.session_id))?.name || "Not assigned"; const fields=[["Student ID",row.student_id],["Email",row.email],["Phone",row.phone],["Father name",row.father_name],["Mother name",row.mother_name],["NRC number",row.nrc_number],["Viber",row.viber_phone],["City",row.city],["Township",row.township],["Birthday",row.birthday],["Gender",row.gender],["Education",row.education],["Status",row.status],["Password",row.password_set ? "Password is set" : "Password not set"],["Course",course],["Session",session]]; return <div className="admin-modal-backdrop"><section className="admin-modal student-modal"><div className="admin-modal-header"><div><p className="admin-eyebrow">STUDENT PROFILE</p><h3>{row.name || "Student details"}</h3></div><button className="admin-icon-button" onClick={onClose}><X size={20}/></button></div>{row.image && <img className="student-detail-image-react" src={row.image} alt={row.name || "Student"}/>}<div className="student-detail-grid-react">{fields.map(([label,value])=><div key={label}><span>{label}</span><b>{value || "Not provided"}</b></div>)}</div></section></div>; }

export default AdminDashboard;
